//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS_70_PeteyPepperoniChallenge
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInformation
    {
        public System.Guid orderID { get; set; }
        public string Size { get; set; }
        public string Crust { get; set; }
        public Nullable<bool> Sausage { get; set; }
        public Nullable<bool> Mushrooms { get; set; }
        public Nullable<bool> BlackOlives { get; set; }
        public Nullable<bool> GreenOlives { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string PaymentMethod { get; set; }
    }
}
